---
title: '225A workshop 2: RStudion & Tidyverse'
author: "Joy Okoro"
date: "2023-10-12"
output: html_notebook
---
#Weather Data Analysis 

```{r load_library}
library(tidyverse)
library(conflicted)
```

```{r Read in data}
sf_weather <- read.csv("raw_data/sf_weather_2023.csv")

head(sf_weather)
colnames(sf_weather)
```


```{r Subset the data}
select (sf_weather, DATE)

#Alternative to above using 'piping'
date <- sf_weather %>%
  select(DATE)
  

```

```{r Subset and split out data}

sf_weather_temp <- sf_weather %>%
  select(c(DATE, TMAX, TMIN)) %>%

#To filter out missing values from the spreadsheet 
   na.omit() %>%
  
#Separate the DATE column into 3 new columns 
  separate(DATE, c("YEAR", "MONTH", "DAY"), sep = "-", remove = FALSE) %>%
  
#Subset to a single year
  dplyr::filter (YEAR == "2021") %>%

#Find the average temp each day 
  mutate(TAVG = ((TMAX+TMIN)/2)) %>%
  
#Group by month 
  group_by(MONTH) %>%
  
#Summarise by grouped data
summarise(MAX_MO_TEMP = max(TAVG))
  
#Display the first few lines of the dataset
head(sf_weather_temp)

#Get the summary info for the dataset
summary(sf_weather_temp)

```

```{r Plotting the data }

plot(sf_weather_temp)

```

```{r Apply functions}

yearly_subsetter <- function(year){
  year_subset <- sf_weather %>%
  select(c(DATE, TMAX, TMIN)) %>%
  na.omit() %>%
  separate(DATE, c("YEAR", "MONTH", "DAY"), sep = "-", remove = FALSE) %>%
  dplyr::filter (YEAR == year) %>%
  mutate(TAVG = ((TMAX+TMIN)/2)) %>%
  group_by(MONTH) %>%
  summarise(MAX_MO_TEMP = max(TAVG))
  
return(year_subset)
}

```

```{r Apply function to data}
year_var <- "1980"

yearly_subsetter(year = year_var)

plot(yearly_subsetter(year = year_var), main = year_var)

```

```{r Apply function with loops, fig.height=6, fig.width=4}

for(my_year_var in c("1970", "1980", "1990", "2000"))
  plot(yearly_subsetter(year = my_year_var), main = my_year_var)


```

